### ISSUE TITLE
DIM* funciont not working

### ISSUE THREAD

**Issue by mattcalavera** [geosim/QAD#12]
When selecting any DIM\* funciont it not work. It says to set the DIMSTYLE before using DIM\* , but whe try to use DIMSTYLE it halts and show this error :

"2016-04-17T12:10:40    1   Traceback (most recent call last):
              File "/Users/XXX/.qgis2/python/plugins/qad/qad.py", line 1621, in runDIMSTYLECommand
                self.runCommandAbortingTheCurrent(QadMsg.translate("Command_list", "DIMSTYLE"))
              File "/Users/XXX/.qgis2/python/plugins/qad/qad.py", line 1375, in runCommandAbortingTheCurrent
                self.showEvaluateMsg(cmdName)
              File "/Users/XXX/.qgis2/python/plugins/qad/qad.py", line 1365, in showEvaluateMsg
                self.TextWindow.showEvaluateMsg(msg)
              File "/Users/XXX/.qgis2/python/plugins/qad/qad_textwindow.py", line 207, in showEvaluateMsg
                self.edit.showEvaluateMsg(msg)
              File "/Users/XXX/.qgis2/python/plugins/qad/qad_textwindow.py", line 870, in showEvaluateMsg
                self.entered()
              File "/Users/XXX/.qgis2/python/plugins/qad/qad_textwindow.py", line 862, in entered
                self.evaluate(unicode(self.currentCommand()))
              File "/Users/XXX/.qgis2/python/plugins/qad/qad_textwindow.py", line 998, in evaluate
                self.parentWidget().runCommand(cmd)
              File "/Users/XXX/.qgis2/python/plugins/qad/qad_textwindow.py", line 219, in runCommand
                self.plugin.runCommand(cmd)
              File "/Users/XXX/.qgis2/python/plugins/qad/qad.py", line 1254, in runCommand
                self.QadCommands.run(command, param)
              File "/Users/XXX/.qgis2/python/plugins/qad/qad_commands.py", line 271, in run
                if self.actualCommand.run() == True: # comando terminato
              File "/Users/XXX/.qgis2/python/plugins/qad/qad_dimstyle_cmd.py", line 70, in run
                Form = QadDIMSTYLEDialog(self.plugIn)
              File "/Users/XXX/.qgis2/python/plugins/qad/qad_dimstyle_dlg.py", line 68, in **init**
                self.init()
              File "/Users/XXX/.qgis2/python/plugins/qad/qad_dimstyle_dlg.py", line 105, in init
                if len(items) > 0:
            UnboundLocalError: local variable 'items' referenced before assignment"

**Comment by gam17** [comment]
fixed !
Thanks for testing QAD

**Comment by mattcalavera** [comment]
When will be available the updated version in the repository?

thanks

MF

2016-04-18 11:04 GMT+02:00 gam17 notifications@github.com:

> fixed !
> Thanks for testing QAD
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/geosim/QAD/issues/12#issuecomment-211284170

## 

Ing. Mattia Fiorini, Ph.D.
Environmental Engineer
Natural and Industrial risk management
+39 347 4752373
mattia.fiorini@gmail.com

**Comment by geosim** [comment]
You can download zip file from github.
We can't publish QAD. You can refer to the closed issue  #11 "Please publish it on the standard repo"
