### ISSUE TITLE
After trying to modify DIM settings all QAD stop working

### ISSUE THREAD

**Issue by mattcalavera** [geosim/QAD#13]
After trying to modify DIM settings all QAD stop working, and checking some snap in settings, all QAD functions stopped working with this error : 

1   Traceback (most recent call last):
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad.py", line 1535, in runLINECommand
                self.runCommandAbortingTheCurrent(QadMsg.translate("Command_list", "LINE"))
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad.py", line 1375, in runCommandAbortingTheCurrent
                self.showEvaluateMsg(cmdName)
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad.py", line 1365, in showEvaluateMsg
                self.TextWindow.showEvaluateMsg(msg)
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_textwindow.py", line 207, in showEvaluateMsg
                self.edit.showEvaluateMsg(msg)
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_textwindow.py", line 870, in showEvaluateMsg
                self.entered()
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_textwindow.py", line 862, in entered
                self.evaluate(unicode(self.currentCommand()))
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_textwindow.py", line 998, in evaluate
                self.parentWidget().runCommand(cmd)
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_textwindow.py", line 219, in runCommand
                self.plugin.runCommand(cmd)
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad.py", line 1254, in runCommand
                self.QadCommands.run(command, param)
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_commands.py", line 271, in run
                if self.actualCommand.run() == True: # comando terminato
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_line_cmd.py", line 160, in run
                self.getPointMapTool().setMode(Qad_line_maptool_ModeEnum.NONE_KNOWN_ASK_FOR_FIRST_PT)
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_line_cmd.py", line 84, in getPointMapTool
                self.PointMapTool = Qad_line_maptool(self.plugIn)
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_line_maptool.py", line 62, in **init**
                QadGetPoint.**init**(self, plugIn)
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_getpoint.py", line 115, in **init**
                self.setSnapType(QadVariables.get(QadMsg.translate("Environment variables", "OSMODE")))
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_getpoint.py", line 349, in setSnapType
                self.updateLayerCacheOnMapCanvasExtent()
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_getpoint.py", line 305, in updateLayerCacheOnMapCanvasExtent
                False)
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_cacheareas.py", line 350, in refreshOnMapCanvasExtent
                self.refreshOnRectOnLayer(layer, rect)
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_cacheareas.py", line 364, in refreshOnRectOnLayer
                return self.insertFeatures(layer, featureList)
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_cacheareas.py", line 289, in insertFeatures
                cacheArea = QadLayerCacheGeoms(layer)
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_cacheareas.py", line 47, in **init**
                self.__create_internal_layer()
              File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_cacheareas.py", line 59, in __create_internal_layer
                str = str + "?crs="
            TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by geosim** [comment]
Can you reproduce the bug step by step ?
I can't reproduce myself.
Explain what you do to generate the error, please.
I will fix as soon as possible (next week)
Thanks for testing QAD

**Comment by mattcalavera** [comment]
Yes, when I enable snap in settings, each action I perform with QAD functions will get this error 👍 

An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'VectorLayer' 
Traceback (most recent call last):
  File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_cacheareas.py", line 373, in onExtentsChanged
    self.onlyEditableLayers)
  File "/Users/mattiafiorini/.qgis2/python/plugins/qad/qad_cacheareas.py", line 333, in refreshOnMapCanvasExtent
    if (layer.type() == QgsMapLayer.VectorLayer) and \
AttributeError: 'NoneType' object has no attribute 'VectorLayer'

Versione Python: 2.7.10 (default, Jul 14 2015, 19:46:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] 
Versione di QGIS: 2.14.0-Essen Essen, exported 

It happens also moving the map with "hand" function.... I'm working on OSX, Qgis Essen, EPSG metric 32632

**Comment by geosim** [comment]
We use windows OS only, never tried OSX.
I have just enabled all QAD snap settings without errors... (dsettings command)
Can you send me a project file and a shape file to test you failure ?
Any detalied infos are apreciated (something like 1) open project, 2) run dsetting command, 3) set x snap type to on, 3) zoom to line x... and so on)
Thanks for testing QAD

**Comment by geosim** [comment]
After 1 month waiting for you without any answer I consider the issue as closed.
