### ISSUE TITLE
Rotate lines specifying an angle throws an exception

### ISSUE THREAD

**Issue by PedroVenancio** [geosim/QAD#7]
When I try to rotate a line freely, everything works fine. Specifying the rotation angle, it throws an exception:

An error has occured while executing Python code:

Traceback (most recent call last):
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_rotate_maptool.py", line 138, in canvasMoveEvent
    self.addRotatedGeometries(angle)
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_rotate_maptool.py", line 129, in addRotatedGeometries
    self.rotate(f, transformedBasePt, angle, layerEntitySet, entitySet)
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_rotate_maptool.py", line 95, in rotate
    dimEntity = self.plugIn.dimStyles.getDimEntity(layerEntitySet.layer, f.id())
AttributeError: 'NoneType' object has no attribute 'id'

Python version:
2.7.6 (default, Jun 22 2015, 18:03:54) 
[GCC 4.8.2]

QGIS version:
2.11.0-Master Master, exported

Python path: ['/home/pedro/QGIS_Debug_10/share/qgis/python/plugins/processing', '/home/pedro/.qgis2/python/plugins/processing_pttransform', '/home/pedro/.qgis2/python/plugins/ntv2_transformations', '/home/pedro/QGIS_Debug_10/share/qgis/python', u'/home/pedro/.qgis2/python', u'/home/pedro/.qgis2/python/plugins', '/home/pedro/QGIS_Debug_10/share/qgis/python/plugins', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-i386-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode', u'/home/pedro/.qgis2//python', '/home/pedro/QGIS_Debug_10/share/qgis/python/plugins/fTools/tools']

An error has occured while executing Python code:

Traceback (most recent call last):
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_getpoint.py", line 612, in keyPressEvent
    self.plugIn.keyPressEvent(event)
  File "/home/pedro/.qgis2/python/plugins/QAD/qad.py", line 1059, in keyPressEvent
    self.TextWindow.keyPressEvent(event)
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_textwindow.py", line 122, in keyPressEvent
    self.edit.keyPressEvent(e)
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_textwindow.py", line 621, in keyPressEvent
    self.entered()
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_textwindow.py", line 670, in entered
    self.evaluate(unicode(self.currentCommand()))
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_textwindow.py", line 924, in evaluate
    self.parentWidget().continueCommand(float(num))
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_textwindow.py", line 170, in continueCommand
    self.plugin.continueCommandFromTextWindow(cmd)
  File "/home/pedro/.qgis2/python/plugins/QAD/qad.py", line 1105, in continueCommandFromTextWindow
    self.QadCommands.continueCommandFromTextWindow(msg)
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_commands.py", line 261, in continueCommandFromTextWindow
    if self.actualCommand.run(False, msg) == True: # comando terminato
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_rotate_cmd.py", line 317, in run
    self.RotateGeoms(angle)
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_rotate_cmd.py", line 161, in RotateGeoms
    if self.rotate(f, transformedBasePt, angle, rotFldName, layerEntitySet, entitySet) == False:
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_rotate_cmd.py", line 100, in rotate
    dimEntity = self.plugIn.dimStyles.getDimEntity(layerEntitySet.layer, f.id())
AttributeError: 'NoneType' object has no attribute 'id'

With polygons, the rotate command works fine with or without specify the angle.

Tested on Xubuntu 14.04 32bits, with QGIS master.

**Comment by geosim** [comment]
Hi Pedro,
   I can't reproduce the bug. Can you download the latest QAD version, retest and report to me, step by step, what I have to do to get the same error.
Thanks for testing

**Comment by PedroVenancio** [comment]
Hi @geosim 
This error is still true to me. Please see this screencast: 

https://dl.dropboxusercontent.com/u/5772257/qgis/qad_rotate_error.ogv 

In this screencast is also visible a problem that happens to me very often. If you look at "QAD text window," when I am entering the angle (90), twice, instead of assuming the insertion of the angle when I click on Enter, it opens a new line. This happens to me constantly when I'm entering commands or parameters in the "text window". Should I open a new ticket for reporting this issue?

Thank you very much!

**Comment by geosim** [comment]
I have installed qgis pisa 2.10 on xubuntu 14.04 but i can't reproduce your problem. Can you send me a shape file and the qgis project file (.qgs) to reproduce the error ?
