### ISSUE TITLE
Help command throws an exception

### ISSUE THREAD

**Issue by PedroVenancio** [geosim/QAD#8]
An error has occured while executing Python code:

Traceback (most recent call last):
  File "/home/pedro/.qgis2/python/plugins/QAD/qad.py", line 1433, in runHELPCommand
    self.runCommandAbortingTheCurrent(QadMsg.translate("Command_list", "HELP"))
  File "/home/pedro/.qgis2/python/plugins/QAD/qad.py", line 1193, in runCommandAbortingTheCurrent
    self.showEvaluateMsg(cmdName)
  File "/home/pedro/.qgis2/python/plugins/QAD/qad.py", line 1184, in showEvaluateMsg
    self.TextWindow.showEvaluateMsg(msg)
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_textwindow.py", line 155, in showEvaluateMsg
    self.edit.showEvaluateMsg(msg)
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_textwindow.py", line 678, in showEvaluateMsg
    self.entered()
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_textwindow.py", line 670, in entered
    self.evaluate(unicode(self.currentCommand()))
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_textwindow.py", line 804, in evaluate
    self.parentWidget().runCommand(cmd)
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_textwindow.py", line 167, in runCommand
    self.plugin.runCommand(cmd)
  File "/home/pedro/.qgis2/python/plugins/QAD/qad.py", line 1096, in runCommand
    self.QadCommands.run(command)
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_commands.py", line 209, in run
    if self.actualCommand.run() == True: # comando terminato
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_help_cmd.py", line 63, in run
    qadShowPluginHelp()
  File "/home/pedro/.qgis2/python/plugins/QAD/qad_msg.py", line 126, in qadShowPluginHelp
    QDesktopServices.openUrl(QUrl(url))
NameError: global name 'QDesktopServices' is not defined

Python version:
2.7.6 (default, Jun 22 2015, 18:03:54) 
[GCC 4.8.2]

QGIS version:
2.11.0-Master Master, exported

Python path: ['/home/pedro/QGIS_Debug_10/share/qgis/python/plugins/processing', '/home/pedro/.qgis2/python/plugins/processing_pttransform', '/home/pedro/.qgis2/python/plugins/ntv2_transformations', '/home/pedro/QGIS_Debug_10/share/qgis/python', u'/home/pedro/.qgis2/python', u'/home/pedro/.qgis2/python/plugins', '/home/pedro/QGIS_Debug_10/share/qgis/python/plugins', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-i386-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode', u'/home/pedro/.qgis2//python', '/home/pedro/QGIS_Debug_10/share/qgis/python/plugins/fTools/tools']

Tested on Xubuntu 14.04 32bits, with QGIS master.

**Comment by geosim** [comment]
Hi Pedro,
   the problem was due to os. I use win 8.1 and you xubuntu. I think it is fixed now. Can you download and retest ?
Thanks for testing
